{
    "name": "singularity-histogram-irec_analysis-job",
    "appId": "singularity-histogram-irec_analysis",
    "appVersion": "0.1",
    "execSystemId": "cedar.computecanada.ca-compute-irec_analysis",
    "memoryMB":4096,
    "maxMinutes":60,
    "parameterSet": {
        "containerArgs": [
        ],
        "appArgs": [
            {"name":"program", "arg":"bash /scratch/ireceptorgw/src/gateway/resources/agave_apps
/histogram/app3.sh"},
            {"name":"split_repertoire", "arg":"True"},
            {"name":"variable", "arg":"junction_aa"},
            {"name":"num_values", "arg":"40"},
            {"name":"sort_values", "arg":"True"}
        ],
        "envVariables": [
            {"key": "singularity_image","value":"/scratch/ireceptorgw/singularity/histogram/histogram-4.0.0.sif"},
            {"key":"ir_gateway_url","value":"https://gateway-analysis-dev.ireceptor.org/"},
            {"key":"download_file","value":"/scratch/ireceptorgw/test/ir_2023-03-09_2358_640a72a18fdeb.zip"},
            {"key":"gateway_util_dir","value":"/scratch/ireceptorgw/src/gateway/public/gateway_utilities"}
        ]
    }
}
