{
    "name": "singularity-statistics-irec_analysis-job",
    "appId": "singularity-statistics-irec_analysis",
    "appVersion": "0.1",
    "execSystemId": "cedar.computecanada.ca-compute-irec_analysis",
    "memoryMB":4096,
    "maxMinutes":60,
    "parameterSet": {
        "containerArgs": [
        ],
        "appArgs": [
            {"name":"split_repertoire", "arg":"True"}
        ],
        "envVariables": [
            {"key": "singularity_image","value":"/scratch/ireceptorgw/singularity/statistics/ir_statistics-4.0.0.sif"},
            {"key":"ir_gateway_url","value":"https://gateway-analysis-dev.ireceptor.org/"},
            {"key":"download_file","value":"/scratch/ireceptorgw/test/ir_2023-03-09_2358_640a72a18fdeb.zip"},
            {"key":"gateway_util_dir","value":"/scratch/ireceptorgw/src/gateway/public/gateway_utilities"}
        ]
    }
}
